name: MemoryMatch
options:
  bundleIdPrefix: com.memorymatch
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  MemoryMatch:
    type: application
    platform: iOS
    sources:
      - path: MemoryMatch
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.memorymatch.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: MemoryMatch/Info.plist
        CODE_SIGN_ENTITLEMENTS: MemoryMatch/MemoryMatch.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
    dependencies:
      - package: Supabase
        product: Supabase
    entitlements:
      path: MemoryMatch/MemoryMatch.entitlements
